### ISSUE TITLE
Moden version of global requires GPATH file to be present

### ISSUE THREAD

**Issue by gshimansky** [juntaki/gogtags#2]
When I try to use global from Emacs I get an error that GPATH file is not found.

**Comment by juntaki** [comment]
gogtags creates GRTAGS,  GTAGS and GPATH.
Could you please give me an example of target source code for reproducing your problem?

**Comment by gshimansky** [comment]
You are right, GPATH file is generated. But nevertheless global complains that it is not found. I am using global - GNU GLOBAL 5.7.1 on Ubuntu 16.04, trying to generate Go tags for this project https://github.com/intel-go/yanff . I get three files generated: GTAGS, GPATH, GRTAGS. Here's what I get:

```$ ls -l G*
-rw-r--r-- 1 gashiman tdc_user  20K Feb  6 07:15 GPATH
-rw-r--r-- 1 gashiman tdc_user 272K Feb  6 07:15 GRTAGS
-rw-r--r-- 1 gashiman tdc_user  64K Feb  6 07:15 GTAGS
$ global -v --result=grep --from-here=43:test/framework/main/tf.go -- RunAllTests
global: GPATH not found
$ global -f GTAGS
global: GPATH not found.
```

Interesting that when I run `gtags` command, I get four generated files: GPATH, GRTAGS, GSYMS and GTAGS instead of three that gogtags generates.

**Comment by juntaki** [comment]
gogtags requires GNU GLOBAL with sqlite3. Please check "GNU GLOBAL Installation for gogtags" at README.

I got the following result on intel-go/yaniff, with global 6.6.1.

~~~
juntaki@ubuntu ~/.g/g/i/yanff> gogtags
juntaki@ubuntu ~/.g/g/i/yanff> global RunAllTests
test/testsuite.go
~~~

**Comment by gshimansky** [comment]
Thank you for clarification. I was sure that Ubuntu builds global with sqlite support. I built my own binary from sources and it works with gogtags now.
I will try to investigate how to submit a patch to Ubuntu to fix this.
