### ISSUE TITLE
Exits when encountering errors

### ISSUE THREAD

**Issue by ChanderG** [juntaki/gogtags#3]
Faced this problem when running in large repos with references to files that don't exist or badly formed. Once gogtags encounters these, it exits then and there instead of ignoring those files and proceeding on.

Have solved this here: https://github.com/ChanderG/gogtags/commit/7e57ea31e404d89673b6585469a0566f6f7dfccf

If there is interest, I can polish it up and submit a PR.

**Comment by juntaki** [comment]
Thanks! Please send your PR.

**Comment by juntaki** [comment]
Closed by #4
