### ISSUE TITLE
GTAGS seems corrupted

### ISSUE THREAD

**Issue by mezeipetister** [juntaki/gogtags#8]
Hi, could you help me please?

I am using Ubuntu 19.04,
1. installed gogtags with go get ...
2. GO_PATH is ok, works weel,
3. GNU Global is already installed as I use it in C dev.
4. In a demo Go project with a main.go and a demo() string {} function I run gogtags
5. GTAGS and others are created, seems to be correct
6. After using global -x demo, it says: GTAGS seems corrupted.

I am using GNU GLOBAL 6.6.3 with Berkley DB 1.85

Could you help me to solve this issue?

**Comment by mezeipetister** [comment]
My apology I missed the --sqlite3 flag. I rebuilt my GNU GLOBAL using sqlite3, and now it works!
Amazing!

**Comment by joecgs** [comment]
try simple project first
